import React, { useState } from 'react';
import {
  Mail,
  Search,
  Filter,
  Plus,
  FileText,
  Send,
  CheckCircle,
  Clock,
  AlertTriangle,
  Eye,
  Sparkles,
  X,
  Check,
  BarChart3,
  ArrowUpRight,
} from 'lucide-react';
import { EmailLog, PurchaseOrder, Vendor } from '../types';

interface EmailCenterProps {
  emails: EmailLog[];
  purchaseOrders: PurchaseOrder[];
  vendors: Vendor[];
  onAddEmailLog: (email: EmailLog) => void;
  onAddActivity: (
    msg: string,
    type: 'PO Updated' | 'Email Sent' | 'Invoice Uploaded' | 'Vendor Comment',
  ) => void;
}

export default function EmailCenter({
  emails,
  purchaseOrders,
  vendors,
  onAddEmailLog,
  onAddActivity,
}: EmailCenterProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  // Composer State
  const [showComposer, setShowComposer] = useState(false);
  const [composerForm, setComposerForm] = useState({
    poId: '',
    subject: '',
    body: '',
    templateId: '',
    attachmentName: '',
  });

  const [aiWriting, setAiWriting] = useState(false);

  // Email Templates for fast sourcing outreach
  const TEMPLATES = [
    {
      id: 'delay',
      name: 'Delayed PO Follow-up',
      subject: 'Production Timeline Check: PO-[NUMBER]',
    },
    {
      id: 'invoice',
      name: 'Missing Invoice Request',
      subject: 'Urgent: Missing Invoice PDF - PO-[NUMBER]',
    },
    {
      id: 'drawing',
      name: 'Specification Check',
      subject: 'Drawings Specifications Approval Check - PO-[NUMBER]',
    },
    {
      id: 'port',
      name: 'Container Logistics Check',
      subject: 'Port Customs Gate Release S&OP - PO-[NUMBER]',
    },
  ];

  // Filter and search email logs
  const filteredEmails = emails.filter((email) => {
    const po = purchaseOrders.find((p) => p.id === email.poId);
    const matchesSearch =
      email.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
      email.poId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (po?.vendorName || '').toLowerCase().includes(searchQuery.toLowerCase());

    const matchesStatus =
      statusFilter === 'all' || email.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  // Apply template variables
  const handleSelectTemplate = (templateId: string) => {
    if (!composerForm.poId) {
      alert(
        'Please select a Purchase Order first to apply template parameters.',
      );
      return;
    }
    const po = purchaseOrders.find((p) => p.id === composerForm.poId);
    if (!po) return;

    const template = TEMPLATES.find((t) => t.id === templateId);
    if (!template) return;

    const formattedSubject = template.subject
      .replace('PO-[NUMBER]', po.id)
      .replace('[NUMBER]', po.id);
    let body = '';

    if (templateId === 'delay') {
      body = `Dear ${po.vendorName} Sourcing Team,

This is a follow-up request regarding Purchase Order ${po.id}. Our records indicate production timelines have exceeded standard thresholds.

The current stage is listed as: ${po.productionStage}.

Please provide an updated production report or container allocation coordinates at your earliest convenience.

Best regards,
S&OP Sourcing Team`;
    } else if (templateId === 'invoice') {
      body = `Dear ${po.vendorName} Finance Coordinator,

We are currently auditing billing documents for Purchase Order ${po.id}.

Please upload the corresponding tax invoice PDF directly to Aerocrm or reply to this thread so our finance desk can authorize the Letter of Credit.

Thank you,
Finance Accounts Payable`;
    } else if (templateId === 'drawing') {
      body = `Dear ${po.vendorName} Engineering Desk,

We would like to confirm specifications sheets validation for the active parts inside PO ${po.id}.

Please confirm drawings parameters matching.

Thank you,
Technical Sourcing Desk`;
    } else if (templateId === 'port') {
      body = `Dear Logistics Dispatch Lead,

Regarding Container ${po.container || 'Pending'} for PO ${po.id}, please confirm if port customs clearance is approved.

Best regards,
Warehouse Logistics`;
    }

    setComposerForm({
      ...composerForm,
      templateId,
      subject: formattedSubject,
      body,
    });
  };

  // Generate Email using AI Sourcing parameters (Rule 10)
  const handleAIGenerate = () => {
    if (!composerForm.poId) {
      alert(
        'Please select a Purchase Order to allow our AI Sourcing Assistant to audit fields.',
      );
      return;
    }

    const po = purchaseOrders.find((p) => p.id === composerForm.poId);
    if (!po) return;

    setAiWriting(true);

    setTimeout(() => {
      const subject = `AI ASSISTANT: Production Status Review - PO ${po.id}`;
      const body = `Dear ${po.vendorName} Sourcing Lead,

This is a customized status review generated by our AI CRM regarding Purchase Order ${po.id} for ${po.orderedQty} units of ${po.items[0]?.name || 'essential items'}.

Currently, the production status of this order is listed as: ${po.status}.
Estimated delivery target: ${po.eta}.

We would appreciate a timeline audit from your manufacturing department to ensure target container arrival schedules match warehouse slots.

Best regards,
Sourcing & S&OP Operations Assistant`;

      setComposerForm({
        ...composerForm,
        subject,
        body,
      });
      setAiWriting(false);
      onAddActivity(
        `AI assistant generated procurement email draft for ${po.id}`,
        'Email Sent',
      );
    }, 1000);
  };

  // Send Composer Form
  const handleSendEmail = (e: React.FormEvent) => {
    e.preventDefault();
    if (!composerForm.poId || !composerForm.subject || !composerForm.body) {
      alert(
        'Please complete the Subject, Body and associated Purchase Order details.',
      );
      return;
    }

    const newEmail: EmailLog = {
      id: `EML-${Math.floor(200 + Math.random() * 800)}`,
      poId: composerForm.poId,
      subject: composerForm.subject,
      sentAt: new Date().toISOString().slice(0, 16).replace('T', ' '),
      status: 'Sent',
      openCount: 0,
      lastOpenTime: null,
      linkClicks: 0,
      repliedAt: null,
      attachmentName: composerForm.attachmentName || null,
    };

    onAddEmailLog(newEmail);
    onAddActivity(
      `Dispatched Sourcing Email outreach: "${composerForm.subject}"`,
      'Email Sent',
    );

    // Reset form
    setComposerForm({
      poId: '',
      subject: '',
      body: '',
      templateId: '',
      attachmentName: '',
    });
    setShowComposer(false);
    alert('Outreach successfully pushed to SMTP pipeline.');
  };

  return (
    <div className="space-y-6">
      {/* Outreach KPI Widget Dashboard (Rule 6) */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs">
          <span className="text-slate-400 text-xs font-semibold block">
            Total Sent Communications
          </span>
          <div className="flex items-center justify-between mt-2">
            <strong className="text-2xl font-display font-bold text-slate-900">
              {emails.length * 3}
            </strong>
            <span className="text-emerald-600 text-[10px] font-bold bg-emerald-50 px-2 py-0.5 rounded-sm flex items-center">
              <ArrowUpRight className="h-3 w-3" />
              <span>+15% Load</span>
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs">
          <span className="text-slate-400 text-xs font-semibold block">
            Average Opened Count
          </span>
          <div className="flex items-center justify-between mt-2">
            <strong className="text-2xl font-display font-bold text-indigo-900">
              85.4%
            </strong>
            <span className="text-emerald-600 text-[10px] font-bold bg-emerald-50 px-2 py-0.5 rounded-sm">
              Optimum
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs">
          <span className="text-slate-400 text-xs font-semibold block">
            Active Click-Through (CTR)
          </span>
          <div className="flex items-center justify-between mt-2">
            <strong className="text-2xl font-display font-bold text-slate-900">
              42.8%
            </strong>
            <span className="text-indigo-600 text-[10px] font-bold bg-indigo-50 px-2 py-0.5 rounded-sm">
              Top Tier
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-xs">
          <span className="text-slate-400 text-xs font-semibold block">
            Sourcing Response Interval
          </span>
          <div className="flex items-center justify-between mt-2">
            <strong className="text-2xl font-display font-bold text-slate-900">
              18.4 Hours
            </strong>
            <span className="text-rose-500 text-[10px] font-bold bg-rose-50 px-2 py-0.5 rounded-sm">
              Needs S&OP Trim
            </span>
          </div>
        </div>
      </div>

      {/* Grid and Composer Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between bg-white p-4 rounded-xl border border-slate-100 shadow-xs gap-4">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search emails by Subject, PO number, Vendor..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg focus:outline-hidden focus:border-indigo-500 focus:bg-white transition text-slate-800"
          />
        </div>

        <div className="flex items-center gap-2">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="text-xs bg-slate-50 border border-slate-200 rounded-lg p-2 focus:outline-hidden text-slate-700 font-semibold"
          >
            <option value="all">All Outreach Statuses</option>
            <option value="Sent">Sent</option>
            <option value="Delivered">Delivered</option>
            <option value="Opened">Opened</option>
            <option value="Replied">Replied</option>
            <option value="Failed">Failed</option>
          </select>

          <button
            onClick={() => setShowComposer(true)}
            className="flex items-center gap-1 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-xs font-bold transition shadow-xs"
          >
            <Plus className="h-3.5 w-3.5" />
            <span>Compose Sourcing Email</span>
          </button>
        </div>
      </div>

      {/* Main Sent Outreach Engagement Table */}
      <div className="bg-white rounded-xl border border-slate-100 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-100 text-slate-500 uppercase tracking-wider font-semibold">
                <th className="px-6 py-4">PO Association</th>
                <th className="px-6 py-4">Subject Outreach / Theme</th>
                <th className="px-6 py-4">Timestamp Sent</th>
                <th className="px-6 py-4">Delivery Status</th>
                <th className="px-6 py-4 text-center">Open Count</th>
                <th className="px-6 py-4 text-center">CTR clicks</th>
                <th className="px-6 py-4 text-center">Response Check</th>
                <th className="px-6 py-4">Attachments</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredEmails.map((email) => {
                const po = purchaseOrders.find((p) => p.id === email.poId);
                return (
                  <tr
                    key={email.id}
                    className="hover:bg-slate-50/70 transition"
                  >
                    <td className="px-6 py-4">
                      <span className="font-bold font-mono text-xs text-slate-800 bg-slate-100 px-2 py-0.5 rounded-sm">
                        {email.poId}
                      </span>
                    </td>
                    <td className="px-6 py-4 font-medium text-slate-800">
                      <div>
                        <span>{email.subject}</span>
                        <p className="text-[10px] text-slate-400 mt-0.5">
                          {po?.vendorName}
                        </p>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-slate-500 font-mono text-xs">
                      {email.sentAt}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                          email.status === 'Replied'
                            ? 'bg-emerald-50 text-emerald-700'
                            : email.status === 'Opened'
                              ? 'bg-indigo-50 text-indigo-700'
                              : email.status === 'Delivered'
                                ? 'bg-sky-50 text-sky-700'
                                : 'bg-slate-100 text-slate-600'
                        }`}
                      >
                        {email.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center font-bold font-mono text-slate-800">
                      {email.openCount}
                    </td>
                    <td className="px-6 py-4 text-center font-bold font-mono text-slate-800">
                      {email.linkClicks}
                    </td>
                    <td className="px-6 py-4 text-center text-slate-600 font-mono">
                      {email.repliedAt ? (
                        <span className="text-emerald-600 font-bold text-[10px] flex items-center justify-center gap-1">
                          <CheckCircle className="h-3.5 w-3.5" />
                          <span>Replied</span>
                        </span>
                      ) : (
                        <span className="text-slate-400 text-[10px]">
                          Awaiting reply
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-slate-500 font-mono text-[10px]">
                      {email.attachmentName ? (
                        <span className="text-indigo-600 font-semibold underline cursor-pointer hover:text-indigo-800 flex items-center gap-1">
                          <FileText className="h-3.5 w-3.5" />
                          <span>{email.attachmentName}</span>
                        </span>
                      ) : (
                        <span className="text-slate-300">-</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* COMPOSER SLIDEOVER MODAL */}
      {showComposer && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs flex items-center justify-end z-50 animate-fadeIn">
          <div className="bg-white h-full max-w-lg w-full p-6 shadow-2xl flex flex-col justify-between border-l border-slate-100 animate-slideLeft">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <h3 className="font-display font-bold text-slate-900 text-base">
                  New Procurement Outreach
                </h3>
                <button
                  onClick={() => setShowComposer(false)}
                  className="p-1.5 hover:bg-slate-100 rounded-lg text-slate-400"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>

              {/* Form details */}
              <div className="space-y-3 text-xs">
                <div>
                  <label className="font-semibold text-slate-600 block mb-1">
                    Target Purchase Order
                  </label>
                  <select
                    value={composerForm.poId}
                    onChange={(e) =>
                      setComposerForm({ ...composerForm, poId: e.target.value })
                    }
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg focus:outline-hidden text-slate-800 font-semibold"
                    required
                  >
                    <option value="">-- Associate Sourcing PO --</option>
                    {purchaseOrders.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.id} - {p.vendorName}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Templates selectors */}
                <div>
                  <label className="font-semibold text-slate-500 block mb-1.5">
                    Apply Procurement Templates
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    {TEMPLATES.map((tmpl) => (
                      <button
                        key={tmpl.id}
                        type="button"
                        onClick={() => handleSelectTemplate(tmpl.id)}
                        className={`p-2 rounded-lg border text-left font-semibold transition hover:border-indigo-400 text-[10px] ${
                          composerForm.templateId === tmpl.id
                            ? 'bg-indigo-50 border-indigo-400 text-indigo-950'
                            : 'bg-white border-slate-200 text-slate-600'
                        }`}
                      >
                        {tmpl.name}
                      </button>
                    ))}
                  </div>
                </div>

                {/* AI Assistant Compose trigger */}
                <div className="bg-indigo-50/50 p-3 rounded-xl border border-indigo-100/50 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4.5 w-4.5 text-indigo-600" />
                    <div>
                      <h4 className="font-semibold text-indigo-950">
                        AI Sourcing Draft Composer
                      </h4>
                      <p className="text-[9px] text-indigo-700 mt-0.5">
                        Let AI review the selected PO and write follow-ups
                        instantly.
                      </p>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={handleAIGenerate}
                    disabled={aiWriting}
                    className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-lg text-[10px] transition"
                  >
                    {aiWriting ? 'Sourcing...' : 'Generate Draft'}
                  </button>
                </div>

                {/* Subject */}
                <div>
                  <label className="font-semibold text-slate-600 block mb-1">
                    Subject outreach
                  </label>
                  <input
                    type="text"
                    placeholder="Enter SMTP Subject header..."
                    value={composerForm.subject}
                    onChange={(e) =>
                      setComposerForm({
                        ...composerForm,
                        subject: e.target.value,
                      })
                    }
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg focus:outline-hidden focus:bg-white text-slate-800 font-medium"
                    required
                  />
                </div>

                {/* Body Textarea */}
                <div>
                  <label className="font-semibold text-slate-600 block mb-1">
                    Email Body Draft
                  </label>
                  <textarea
                    placeholder="Provide detailed instructions to the manufacturer..."
                    value={composerForm.body}
                    onChange={(e) =>
                      setComposerForm({ ...composerForm, body: e.target.value })
                    }
                    rows={8}
                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg focus:outline-hidden focus:bg-white text-slate-800 leading-relaxed font-mono"
                    required
                  />
                </div>

                {/* Attachment */}
                <div>
                  <label className="font-semibold text-slate-600 block mb-1">
                    Add Procurement Attachment (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g., technical_drawing_revision.pdf"
                    value={composerForm.attachmentName}
                    onChange={(e) =>
                      setComposerForm({
                        ...composerForm,
                        attachmentName: e.target.value,
                      })
                    }
                    className="w-full p-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-hidden font-mono"
                  />
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2 border-t border-slate-100 pt-4 mt-4">
              <button
                type="button"
                onClick={() => setShowComposer(false)}
                className="px-4 py-2 border border-slate-200 text-slate-600 rounded-lg text-xs font-medium"
              >
                Discard Draft
              </button>
              <button
                type="button"
                onClick={handleSendEmail}
                className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition shadow-xs flex items-center gap-1"
              >
                <Send className="h-3 w-3" />
                <span>Dispatch SMTP Pipeline</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
