import React, { useState } from 'react';
import {
  Mail,
  Search,
  Filter,
  Plus,
  FileText,
  Send,
  CheckCircle,
  Clock,
  AlertTriangle,
  Eye,
  Sparkles,
  X,
  Check,
  BarChart3,
  ArrowUpRight,
} from 'lucide-react';
import { EmailLog, PurchaseOrder, Vendor } from '../types';

interface EmailCenterProps {
  emails: EmailLog[];
  purchaseOrders: PurchaseOrder[];
  vendors: Vendor[];
  onAddEmailLog: (email: EmailLog) => void;
  onAddActivity: (
    msg: string,
    type: 'PO Updated' | 'Email Sent' | 'Invoice Uploaded' | 'Vendor Comment',
  ) => void;
}

export default function EmailCenter({
  emails,
  purchaseOrders,
  vendors,
  onAddEmailLog,
  onAddActivity,
}: EmailCenterProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  // Composer State
  const [showComposer, setShowComposer] = useState(false);
  const [composerForm, setComposerForm] = useState({
    poId: '',
    subject: '',
    body: '',
    templateId: '',
    attachmentName: '',
  });

  const [aiWriting, setAiWriting] = useState(false);

  // Email Templates for fast sourcing outreach
  const TEMPLATES = [
    {
      id: 'delay',
      name: 'Delayed PO Follow-up',
      subject: 'Production Timeline Check: PO-[NUMBER]',
    },
    {
      id: 'invoice',
      name: 'Missing Invoice Request',
      subject: 'Urgent: Missing Invoice PDF - PO-[NUMBER]',
    },
    {
      id: 'drawing',
      name: 'Specification Check',
      subject: 'Drawings Specifications Approval Check - PO-[NUMBER]',
    },
    {
      id: 'port',
      name: 'Container Logistics Check',
      subject: 'Port Customs Gate Release S&OP - PO-[NUMBER]',
    },
  ];

  // Filter and search email logs
  const filteredEmails = emails.filter((email) => {
    const po = purchaseOrders.find((p) => p.id === email.poId);
    const matchesSearch =
      email.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
      email.poId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (po?.vendorName || '').toLowerCase().includes(searchQuery.toLowerCase());

    const matchesStatus =
      statusFilter === 'all' || email.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  // Apply template variables
  const handleSelectTemplate = (templateId: string) => {
    if (!composerForm.poId) {
      alert(
        'Please select a Purchase Order first to apply template parameters.',
      );
      return;
    }
    const po = purchaseOrders.find((p) => p.id === composerForm.poId);
    if (!po) return;

    const template = TEMPLATES.find((t) => t.id === templateId);
    if (!template) return;

    const formattedSubject = template.subject
      .replace('PO-[NUMBER]', po.id)
      .replace('[NUMBER]', po.id);
    let body = '';

    if (templateId === 'delay') {
      body = `Dear ${po.vendorName} Sourcing Team,

This is a follow-up request regarding Purchase Order ${po.id}. Our records indicate production timelines have exceeded standard thresholds.

The current stage is listed as: ${po.productionStage}.

Please provide an updated production report or container allocation coordinates at your earliest convenience.

Best regards,
S&OP Sourcing Team`;
    } else if (templateId === 'invoice') {
      body = `Dear ${po.vendorName} Finance Coordinator,

We are currently auditing billing documents for Purchase Order ${po.id}.

Please upload the corresponding tax invoice PDF directly to Aerocrm or reply to this thread so our finance desk can authorize the Letter of Credit.

Thank you,
Finance Accounts Payable`;
    } else if (templateId === 'drawing') {
      body = `Dear ${po.vendorName} Engineering Desk,

We would like to confirm specifications sheets validation for the active parts inside PO ${po.id}.

Please confirm drawings parameters matching.

Thank you,
Technical Sourcing Desk`;
    } else if (templateId === 'port') {
      body = `Dear Logistics Dispatch Lead,

Regarding Container ${po.container || 'Pending'} for PO ${po.id}, please confirm if port customs clearance is approved.

Best regards,
Warehouse Logistics`;
    }

    setComposerForm({
      ...composerForm,
      templateId,
      subject: formattedSubject,
      body,
    });
  };

  // Generate Email using AI Sourcing parameters (Rule 10)
  const handleAIGenerate = () => {
    if (!composerForm.poId) {
      alert(
        'Please select a Purchase Order to allow our AI Sourcing Assistant to audit fields.',
      );
      return;
    }

    const po = purchaseOrders.find((p) => p.id === composerForm.poId);
    if (!po) return;

    setAiWriting(true);

    setTimeout(() => {
      const subject = `AI ASSISTANT: Production Status Review - PO ${po.id}`;
      const body = `Dear ${po.vendorName} Sourcing Lead,

This is a customized status review generated by our AI CRM regarding Purchase Order ${po.id} for ${po.orderedQty} units of ${po.items[0]?.name || 'essential items'}.

Currently, the production status of this order is listed as: ${po.status}.
Estimated delivery target: ${po.eta}.

We would appreciate a timeline audit from your manufacturing department to ensure target container arrival schedules match warehouse slots.

Best regards,
Sourcing & S&OP Operations Assistant`;

      setComposerForm({
        ...composerForm,
        subject,
        body,
      });
      setAiWriting(false);
      onAddActivity(
        `AI assistant generated procurement email draft for ${po.id}`,
        'Email Sent',
      );
    }, 1000);
  };

  // Send Composer Form
  const handleSendEmail = (e: React.FormEvent) => {
    e.preventDefault();
    if (!composerForm.poId || !composerForm.subject || !composerForm.body) {
      alert(
        'Please complete the Subject, Body and associated Purchase Order details.',
      );
      return;
    }

    const newEmail: EmailLog = {
      id: `EML-${Math.floor(200 + Math.random() * 800)}`,
      poId: composerForm.poId,
      subject: composerForm.subject,
      sentAt: new Date().toISOString().slice(0, 16).replace('T', ' '),
      status: 'Sent',
      openCount: 0,
      lastOpenTime: null,
      linkClicks: 0,
      repliedAt: null,
      attachmentName: composerForm.attachmentName || null,
    };

    onAddEmailLog(newEmail);
    onAddActivity(
      `Dispatched Sourcing Email outreach: "${composerForm.subject}"`,
      'Email Sent',
    );

    // Reset form
    setComposerForm({
      poId: '',
      subject: '',
      body: '',
      templateId: '',
      attachmentName: '',
    });
    setShowComposer(false);
    alert('Outreach successfully pushed to SMTP pipeline.');
  };

  return (
    <div className="space-y-6">
      {/* Outreach KPI Widget Dashboard (Rule 6) */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-4">
        <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-xs">
          <span className="block text-xs font-semibold text-slate-400">
            Total Sent Communications
          </span>
          <div className="mt-2 flex items-center justify-between">
            <strong className="font-display text-2xl font-bold text-slate-900">
              {emails.length * 3}
            </strong>
            <span className="flex items-center rounded-sm bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-600">
              <ArrowUpRight className="h-3 w-3" />
              <span>+15% Load</span>
            </span>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-xs">
          <span className="block text-xs font-semibold text-slate-400">
            Average Opened Count
          </span>
          <div className="mt-2 flex items-center justify-between">
            <strong className="font-display text-2xl font-bold text-indigo-900">
              85.4%
            </strong>
            <span className="rounded-sm bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-600">
              Optimum
            </span>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-xs">
          <span className="block text-xs font-semibold text-slate-400">
            Active Click-Through (CTR)
          </span>
          <div className="mt-2 flex items-center justify-between">
            <strong className="font-display text-2xl font-bold text-slate-900">
              42.8%
            </strong>
            <span className="rounded-sm bg-indigo-50 px-2 py-0.5 text-[10px] font-bold text-indigo-600">
              Top Tier
            </span>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-xs">
          <span className="block text-xs font-semibold text-slate-400">
            Sourcing Response Interval
          </span>
          <div className="mt-2 flex items-center justify-between">
            <strong className="font-display text-2xl font-bold text-slate-900">
              18.4 Hours
            </strong>
            <span className="rounded-sm bg-rose-50 px-2 py-0.5 text-[10px] font-bold text-rose-500">
              Needs S&OP Trim
            </span>
          </div>
        </div>
      </div>

      {/* Grid and Composer Controls */}
      <div className="flex flex-col gap-4 rounded-xl border border-slate-100 bg-white p-4 shadow-xs sm:flex-row sm:items-center sm:justify-between">
        <div className="relative max-w-md flex-1">
          <Search className="absolute top-2.5 left-3 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search emails by Subject, PO number, Vendor..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pr-4 pl-9 text-xs text-slate-800 transition focus:border-indigo-500 focus:bg-white focus:outline-hidden"
          />
        </div>

        <div className="flex items-center gap-2">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="rounded-lg border border-slate-200 bg-slate-50 p-2 text-xs font-semibold text-slate-700 focus:outline-hidden"
          >
            <option value="all">All Outreach Statuses</option>
            <option value="Sent">Sent</option>
            <option value="Delivered">Delivered</option>
            <option value="Opened">Opened</option>
            <option value="Replied">Replied</option>
            <option value="Failed">Failed</option>
          </select>

          <button
            onClick={() => setShowComposer(true)}
            className="flex items-center gap-1 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white shadow-xs transition hover:bg-indigo-700"
          >
            <Plus className="h-3.5 w-3.5" />
            <span>Compose Sourcing Email</span>
          </button>
        </div>
      </div>

      {/* Main Sent Outreach Engagement Table */}
      <div className="overflow-hidden rounded-xl border border-slate-100 bg-white shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-left text-xs">
            <thead>
              <tr className="border-b border-slate-100 bg-slate-50 font-semibold tracking-wider text-slate-500 uppercase">
                <th className="px-6 py-4">PO Association</th>
                <th className="px-6 py-4">Subject Outreach / Theme</th>
                <th className="px-6 py-4">Timestamp Sent</th>
                <th className="px-6 py-4">Delivery Status</th>
                <th className="px-6 py-4 text-center">Open Count</th>
                <th className="px-6 py-4 text-center">CTR clicks</th>
                <th className="px-6 py-4 text-center">Response Check</th>
                <th className="px-6 py-4">Attachments</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredEmails.map((email) => {
                const po = purchaseOrders.find((p) => p.id === email.poId);
                return (
                  <tr
                    key={email.id}
                    className="transition hover:bg-slate-50/70"
                  >
                    <td className="px-6 py-4">
                      <span className="rounded-sm bg-slate-100 px-2 py-0.5 font-mono text-xs font-bold text-slate-800">
                        {email.poId}
                      </span>
                    </td>
                    <td className="px-6 py-4 font-medium text-slate-800">
                      <div>
                        <span>{email.subject}</span>
                        <p className="mt-0.5 text-[10px] text-slate-400">
                          {po?.vendorName}
                        </p>
                      </div>
                    </td>
                    <td className="px-6 py-4 font-mono text-xs text-slate-500">
                      {email.sentAt}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${
                          email.status === 'Replied'
                            ? 'bg-emerald-50 text-emerald-700'
                            : email.status === 'Opened'
                              ? 'bg-indigo-50 text-indigo-700'
                              : email.status === 'Delivered'
                                ? 'bg-sky-50 text-sky-700'
                                : 'bg-slate-100 text-slate-600'
                        }`}
                      >
                        {email.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center font-mono font-bold text-slate-800">
                      {email.openCount}
                    </td>
                    <td className="px-6 py-4 text-center font-mono font-bold text-slate-800">
                      {email.linkClicks}
                    </td>
                    <td className="px-6 py-4 text-center font-mono text-slate-600">
                      {email.repliedAt ? (
                        <span className="flex items-center justify-center gap-1 text-[10px] font-bold text-emerald-600">
                          <CheckCircle className="h-3.5 w-3.5" />
                          <span>Replied</span>
                        </span>
                      ) : (
                        <span className="text-[10px] text-slate-400">
                          Awaiting reply
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4 font-mono text-[10px] text-slate-500">
                      {email.attachmentName ? (
                        <span className="flex cursor-pointer items-center gap-1 font-semibold text-indigo-600 underline hover:text-indigo-800">
                          <FileText className="h-3.5 w-3.5" />
                          <span>{email.attachmentName}</span>
                        </span>
                      ) : (
                        <span className="text-slate-300">-</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* COMPOSER SLIDEOVER MODAL */}
      {showComposer && (
        <div className="animate-fadeIn fixed inset-0 z-50 flex items-center justify-end bg-slate-900/40 backdrop-blur-xs">
          <div className="animate-slideLeft flex h-full w-full max-w-lg flex-col justify-between border-l border-slate-100 bg-white p-6 shadow-2xl">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <h3 className="font-display text-base font-bold text-slate-900">
                  New Procurement Outreach
                </h3>
                <button
                  onClick={() => setShowComposer(false)}
                  className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>

              {/* Form details */}
              <div className="space-y-3 text-xs">
                <div>
                  <label className="mb-1 block font-semibold text-slate-600">
                    Target Purchase Order
                  </label>
                  <select
                    value={composerForm.poId}
                    onChange={(e) =>
                      setComposerForm({ ...composerForm, poId: e.target.value })
                    }
                    className="w-full rounded-lg border border-slate-200 bg-slate-50 p-2.5 font-semibold text-slate-800 focus:outline-hidden"
                    required
                  >
                    <option value="">-- Associate Sourcing PO --</option>
                    {purchaseOrders.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.id} - {p.vendorName}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Templates selectors */}
                <div>
                  <label className="mb-1.5 block font-semibold text-slate-500">
                    Apply Procurement Templates
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    {TEMPLATES.map((tmpl) => (
                      <button
                        key={tmpl.id}
                        type="button"
                        onClick={() => handleSelectTemplate(tmpl.id)}
                        className={`rounded-lg border p-2 text-left text-[10px] font-semibold transition hover:border-indigo-400 ${
                          composerForm.templateId === tmpl.id
                            ? 'border-indigo-400 bg-indigo-50 text-indigo-950'
                            : 'border-slate-200 bg-white text-slate-600'
                        }`}
                      >
                        {tmpl.name}
                      </button>
                    ))}
                  </div>
                </div>

                {/* AI Assistant Compose trigger */}
                <div className="flex items-center justify-between rounded-xl border border-indigo-100/50 bg-indigo-50/50 p-3">
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4.5 w-4.5 text-indigo-600" />
                    <div>
                      <h4 className="font-semibold text-indigo-950">
                        AI Sourcing Draft Composer
                      </h4>
                      <p className="mt-0.5 text-[9px] text-indigo-700">
                        Let AI review the selected PO and write follow-ups
                        instantly.
                      </p>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={handleAIGenerate}
                    disabled={aiWriting}
                    className="rounded-lg bg-indigo-600 px-3 py-1.5 text-[10px] font-bold text-white transition hover:bg-indigo-700"
                  >
                    {aiWriting ? 'Sourcing...' : 'Generate Draft'}
                  </button>
                </div>

                {/* Subject */}
                <div>
                  <label className="mb-1 block font-semibold text-slate-600">
                    Subject outreach
                  </label>
                  <input
                    type="text"
                    placeholder="Enter SMTP Subject header..."
                    value={composerForm.subject}
                    onChange={(e) =>
                      setComposerForm({
                        ...composerForm,
                        subject: e.target.value,
                      })
                    }
                    className="w-full rounded-lg border border-slate-200 bg-slate-50 p-2.5 font-medium text-slate-800 focus:bg-white focus:outline-hidden"
                    required
                  />
                </div>

                {/* Body Textarea */}
                <div>
                  <label className="mb-1 block font-semibold text-slate-600">
                    Email Body Draft
                  </label>
                  <textarea
                    placeholder="Provide detailed instructions to the manufacturer..."
                    value={composerForm.body}
                    onChange={(e) =>
                      setComposerForm({ ...composerForm, body: e.target.value })
                    }
                    rows={8}
                    className="w-full rounded-lg border border-slate-200 bg-slate-50 p-2.5 font-mono leading-relaxed text-slate-800 focus:bg-white focus:outline-hidden"
                    required
                  />
                </div>

                {/* Attachment */}
                <div>
                  <label className="mb-1 block font-semibold text-slate-600">
                    Add Procurement Attachment (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g., technical_drawing_revision.pdf"
                    value={composerForm.attachmentName}
                    onChange={(e) =>
                      setComposerForm({
                        ...composerForm,
                        attachmentName: e.target.value,
                      })
                    }
                    className="w-full rounded-lg border border-slate-200 bg-slate-50 p-2 font-mono focus:outline-hidden"
                  />
                </div>
              </div>
            </div>

            <div className="mt-4 flex justify-end gap-2 border-t border-slate-100 pt-4">
              <button
                type="button"
                onClick={() => setShowComposer(false)}
                className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-medium text-slate-600"
              >
                Discard Draft
              </button>
              <button
                type="button"
                onClick={handleSendEmail}
                className="flex items-center gap-1 rounded-lg bg-indigo-600 px-5 py-2 text-xs font-bold text-white shadow-xs transition hover:bg-indigo-700"
              >
                <Send className="h-3 w-3" />
                <span>Dispatch SMTP Pipeline</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
